name: Publish

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56.0
          override: true
          components: rustfmt, clippy
      - name: Install WASM Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      - name: Build
        run:  wasm-pack build
      - name: Set ENV
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update package version
        run: npm version ${{ env.RELEASE_VERSION }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
